# Generated by Django 4.2.9 on 2024-04-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csmoney_allowed_discount', models.FloatField(default=0.35)),
                ('steam_allowed_profit', models.FloatField(default=1.35)),
                ('page_count', models.IntegerField(default=180)),
                ('time_to_update', models.IntegerField(default=24)),
                ('parse_on_start', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('csmoney_price', models.FloatField()),
                ('steam_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('found_date', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desired_profit', models.FloatField(default=1.35)),
                ('notify', models.BooleanField(default=True)),
                ('language', models.CharField(default='ua', max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
